name: "check"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  mypy:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Python"
        run: |
          cd ./python/
          python -m venv venv
          ./venv/bin/pip install -r requirements.txt

      - name: "mypy"
        run: |
          cd ./python/
          ./venv/bin/mypy .
